# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration for an example

name = "HTML ARIA Hugo Theme"
license = "MIT"
licenselink = "Link to theme's license"
description = "HTML5 ARIA compliant Hugo theme, using BEM CSS methodology, but lacking any CSS styling."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/biapy/html-aria-hugo-theme"

# If you have a running demo of the theme.
# demosite = "https://gohugo.io"

tags = ["a11y", "accessibility", "html5", "aria", "biapy"]
features = ["aria", "a11y", "html5"]

# If the theme has a single author
[author]
    name = "Pierre-Yves LANDURÉ"
    homepage = "https://howto.biapy.com/"
